#!/bin/bash

aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-1"}, "Name": {"S": "Delaware"}, "Abbreviation": {"S": "DE"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-2"}, "Name": {"S": "Pennsylvania"}, "Abbreviation": {"S": "PA"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-3"}, "Name": {"S": "New Jersey"}, "Abbreviation": {"S": "NJ"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-4"}, "Name": {"S": "Georgia"}, "Abbreviation": {"S": "GA"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-5"}, "Name": {"S": "Connecticut"}, "Abbreviation": {"S": "CT"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-6"}, "Name": {"S": "Massachusetts"}, "Abbreviation": {"S": "MA"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-7"}, "Name": {"S": "Maryland"}, "Abbreviation": {"S": "MD"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-8"}, "Name": {"S": "South Carolina"}, "Abbreviation": {"S": "SC"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-9"}, "Name": {"S": "New Hampshire"}, "Abbreviation": {"S": "NH"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-10"}, "Name": {"S": "Virginia"}, "Abbreviation": {"S": "VA"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-11"}, "Name": {"S": "New York"}, "Abbreviation": {"S": "NY"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-12"}, "Name": {"S": "North Carolina"}, "Abbreviation": {"S": "NC"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-13"}, "Name": {"S": "Rhode Island"}, "Abbreviation": {"S": "RI"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-14"}, "Name": {"S": "Vermont"}, "Abbreviation": {"S": "VT"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-15"}, "Name": {"S": "Kentucky"}, "Abbreviation": {"S": "KY"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-16"}, "Name": {"S": "Tennessee"}, "Abbreviation": {"S": "TN"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-17"}, "Name": {"S": "Ohio"}, "Abbreviation": {"S": "OH"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-18"}, "Name": {"S": "Louisiana"}, "Abbreviation": {"S": "LA"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-19"}, "Name": {"S": "Indiana"}, "Abbreviation": {"S": "IN"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-20"}, "Name": {"S": "Mississippi"}, "Abbreviation": {"S": "MS"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-21"}, "Name": {"S": "Illinois"}, "Abbreviation": {"S": "IL"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-22"}, "Name": {"S": "Alabama"}, "Abbreviation": {"S": "AL"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-23"}, "Name": {"S": "Maine"}, "Abbreviation": {"S": "ME"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-24"}, "Name": {"S": "Missouri"}, "Abbreviation": {"S": "MO"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-25"}, "Name": {"S": "Arkansas"}, "Abbreviation": {"S": "AR"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-26"}, "Name": {"S": "Michigan"}, "Abbreviation": {"S": "MI"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-27"}, "Name": {"S": "Florida"}, "Abbreviation": {"S": "FL"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-28"}, "Name": {"S": "Texas"}, "Abbreviation": {"S": "TX"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-29"}, "Name": {"S": "Iowa"}, "Abbreviation": {"S": "IA"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-30"}, "Name": {"S": "Wisconsin"}, "Abbreviation": {"S": "WI"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-31"}, "Name": {"S": "California"}, "Abbreviation": {"S": "CA"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-32"}, "Name": {"S": "Minnesota"}, "Abbreviation": {"S": "MN"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-33"}, "Name": {"S": "Oregon"}, "Abbreviation": {"S": "OR"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-34"}, "Name": {"S": "Kansas"}, "Abbreviation": {"S": "KS"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-35"}, "Name": {"S": "West Virginia"}, "Abbreviation": {"S": "WV"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-36"}, "Name": {"S": "Nevada"}, "Abbreviation": {"S": "NV"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-37"}, "Name": {"S": "Nebraska"}, "Abbreviation": {"S": "NE"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-38"}, "Name": {"S": "Colorado"}, "Abbreviation": {"S": "CO"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-39"}, "Name": {"S": "North Dakota"}, "Abbreviation": {"S": "ND"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-40"}, "Name": {"S": "South Dakota"}, "Abbreviation": {"S": "SD"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-41"}, "Name": {"S": "Montana"}, "Abbreviation": {"S": "MT"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-42"}, "Name": {"S": "Washington"}, "Abbreviation": {"S": "WA"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-43"}, "Name": {"S": "Idaho"}, "Abbreviation": {"S": "ID"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-44"}, "Name": {"S": "Wyoming"}, "Abbreviation": {"S": "WY"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-45"}, "Name": {"S": "Utah"}, "Abbreviation": {"S": "UT"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-46"}, "Name": {"S": "Oklahoma"}, "Abbreviation": {"S": "OK"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-47"}, "Name": {"S": "New Mexico"}, "Abbreviation": {"S": "NM"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-48"}, "Name": {"S": "Arizona"}, "Abbreviation": {"S": "AZ"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-49"}, "Name": {"S": "Alaska"}, "Abbreviation": {"S": "AK"}}'
aws dynamodb put-item --table-name UnitedStates --item  '{"Id": {"S": "S-50"}, "Name": {"S": "Hawaii"}, "Abbreviation": {"S": "HI"}}'
